### PR TITLE
Full Demo Deployment Steps for Bash

### PR DESCRIPTION
**Pull request by kendallroden**
I created demo.sh which a customer can walk through to deploy all of the resources associated with this demo and provide their own values. I realized there is nowhere we walk users through the creation of things like ACR, Service Bus, etc.  I also added a way for them to save environment variables in case they want to return to the work later and lose their bash session. I will eventually add a readme and make the script automated. We can also add support for ARM, Bicep, or YAML style deployments

### CODE REVIEW

**Comment by kendallroden** [comment]
@andreatosato hopefully this will make it easy for others to deploy step by step to their own subs! Happy to continue contributing if you'll take it :)

**Comment by andreatosato** [comment]
♥️ @kendallroden  thank you!

I want to add bicep, readme, architecture diagram... 

I have another repository where I use also secrets.
Can I use azure keyvault with dapr? Can I use container apps secrets and Dapr? 
For next Friday demo I add setting manually but I want to add also this feature.


Last improvement that I want to do are:
- add redis in container apps and use it (not service bus)
- add opentelemetry (now is not supported in azure container apps)

**Comment by andreatosato** [comment]
https://github.com/andreatosato/SpotifyMicroservices/tree/feature/container-apps

**Comment by kendallroden** [comment]
Can I use azure keyvault with dapr? Can I use container apps secrets and Dapr?
- Currently, we do not integrate with Key Vault but it is planned on the roadmap. Also right now, we support all secrets via. the secrets container app spec, we don't support the native dapr secrets feature but we are having conversations now around this topic. 

Last improvement that I want to do are:

add redis in container apps and use it (not service bus)
- We don't support running Redis in Container Apps today as it relies on TCP- we also don't have any support for Azure Files/Disk atm for stateful workloads
add opentelemetry (now is not supported in azure container apps)

**Pull request merged**
